# Generated by Django 5.2 on 2025-04-18 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PieceOfContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500)),
                ('content_type', models.CharField(choices=[('tiktok', 'Tiktok'), ('tweet', 'Tweet'), ('blog_post', 'Blog Post'), ('reddit_post', 'Reddit Post'), ('reddit_answer', 'Reddit Answer'), ('hn_post', 'Hn Post'), ('hn_comment', 'Hn Comment'), ('other', 'Other')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_projects_folder', models.CharField(max_length=200)),
                ('github_token', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('current_priority', 'Current Priority'), ('online', 'Online'), ('on_ice', 'On Ice'), ('dead', 'Dead'), ('stub', 'Stub'), ('unknown', 'Unknown')], default='unknown', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.metaproject')),
            ],
        ),
        migrations.CreateModel(
            name='GoatcounterTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goatcounter_id', models.CharField(max_length=200)),
                ('api_key', models.CharField(max_length=200)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.project')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('metadata_last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_file_change', models.DateTimeField(blank=True, null=True)),
                ('still_exists', models.BooleanField(default=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.project')),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('deployment_provider', models.CharField(choices=[('heroku', 'Heroku'), ('netlify', 'Netlify'), ('github_pages', 'Github Pages'), ('other', 'Other')], max_length=200)),
                ('should_track_pageviews', models.BooleanField(default=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.project')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('metadata_last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('nr_issues', models.IntegerField(blank=True, null=True)),
                ('nr_open_issues', models.IntegerField(blank=True, null=True)),
                ('last_commit_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.project')),
            ],
        ),
    ]
