# Generated by Django 5.2 on 2025-04-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
