# Generated by Django 5.2 on 2025-04-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_project_auto_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceofcontent',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pieceofcontent',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='hn_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='reddit_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='tiktok_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='twitter_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pieceofcontent',
            name='link',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='github_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='local_projects_folder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
