# Generated by Django 5.2 on 2025-04-18 18:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_pieceofcontent_likes_pieceofcontent_views_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceofcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pieceofcontent',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
