# Generated by Django 5.2 on 2025-04-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_pieceofcontent_created_at_pieceofcontent_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='deployment_provider',
            field=models.CharField(choices=[('heroku', 'Heroku'), ('netlify', 'Netlify'), ('github_pages', 'GitHub Pages'), ('other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='pieceofcontent',
            name='content_type',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('tweet', 'Tweet'), ('blog_post', 'Blog Post'), ('reddit_post', 'Reddit Post'), ('reddit_answer', 'Reddit Answer'), ('hn_post', 'Hacker News Post'), ('hn_comment', 'Hacker News Comment'), ('other', 'Other')], max_length=200),
        ),
    ]
