# Generated by Django 5.2 on 2025-04-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_deployment_deployment_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='tiktok_ms_token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
