# Generated by Django 5.2 on 2025-04-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_settings_tiktok_ms_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='twitter_access_token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='twitter_access_token_secret',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='twitter_api_key',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='twitter_api_secret',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='twitter_bearer_token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
