# Generated by Django 5.2 on 2025-04-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_settings_twitter_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='linked_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
