# Generated by Django 5.2 on 2025-04-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_repository_linked_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
