# Generated by Django 5.2 on 2025-04-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_remove_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='should_track_pageviews',
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deployment_provider',
            field=models.CharField(choices=[('heroku', 'Heroku'), ('netlify', 'Netlify'), ('github_pages', 'GitHub Pages'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=200),
        ),
    ]
