# Generated by Django 5.2 on 2025-04-21 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_remove_deployment_should_track_pageviews_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.IntegerField()),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.project')),
            ],
            options={
                'unique_together': {('date', 'project')},
            },
        ),
    ]
