# Generated by Django 5.2 on 2025-04-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_pageviewday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiktok_goal_type', models.CharField(choices=[('none', 'None'), ('day_based', 'Day-based'), ('week_based', 'Week-based'), ('month_based', 'Month-based')], default='none', max_length=200)),
                ('tiktok_streak_goal', models.IntegerField(default=0)),
                ('tiktok_milestone_goal', models.IntegerField(default=0)),
                ('twitter_goal_type', models.CharField(choices=[('none', 'None'), ('day_based', 'Day-based'), ('week_based', 'Week-based'), ('month_based', 'Month-based')], default='none', max_length=200)),
                ('twitter_streak_goal', models.IntegerField(default=0)),
                ('twitter_milestone_goal', models.IntegerField(default=0)),
                ('reddit_goal_type', models.CharField(choices=[('none', 'None'), ('day_based', 'Day-based'), ('week_based', 'Week-based'), ('month_based', 'Month-based')], default='none', max_length=200)),
                ('reddit_streak_goal', models.IntegerField(default=0)),
                ('reddit_milestone_goal', models.IntegerField(default=0)),
            ],
        ),
    ]
