# Generated by Django 5.2 on 2025-05-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='obsidian_projects_folder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
